import React from 'react'
import Breadcrumb from '../../components/Breadcrumb'
import Meta from '../../components/Meta'

function Terms() {
  return (
    <>
        <Meta head="Terms & Conditions"/>
        <Breadcrumb tittle="Terms & Conditions" />
        <main className='bg-gray-200 py-4'>
            <div className='max-w-7xl space-y-2 bg-white px-12 py-8 flex-col rounded-lg mx-auto flex '>
                <p className='font-medium text-lg text-black'>Eshoppers Terms of Use</p>  
                <p className='font-medium text-base text-black'>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>  
                <p className='font-medium text-base text-black pt-2'>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name [www.Eshoppers.com][www.Eshoppers.com] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)</p>  
                <p className='font-normal text-base text-black pt-2'>Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Eshoppers Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with Eshoppers.</p>  
                <p className='font-normal text-base text-black pt-2'>When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform.</p>  

            </div>
        </main>
    </>
  )
}

export default Terms